unit MobilePermissions.UsesPermissions.OTA.Constants;

interface

const
  AUP_ACCESS_LOCATION_EXTRA_COMMANDS = 'AUP_ACCESS_LOCATION_EXTRA_COMMANDS';
  AUP_ACCESS_NETWORK_STATE = 'AUP_ACCESS_NETWORK_STATE';
  AUP_ACCESS_NOTIFICATION_POLICY = 'AUP_ACCESS_NOTIFICATION_POLICY';
  AUP_ACCESS_WIFI_STATE = 'AUP_ACCESS_WIFI_STATE';
  AUP_BATTERY_STATS = 'AUP_BATTERY_STATS';
  AUP_BLUETOOTH = 'AUP_BLUETOOTH';
  AUP_BLUETOOTH_ADMIN = 'AUP_BLUETOOTH_ADMIN';
  AUP_BROADCAST_STICKY = 'AUP_BROADCAST_STICKY';
  //Por algum motivo, não existe CALL_COMPANION_APP no JavaClass. Desativamos a propriedade
  //AUP_CALL_COMPANION_APP = 'AUP_CALL_COMPANION_APP';
  AUP_CHANGE_CONFIGURATION = 'AUP_CHANGE_CONFIGURATION';
  AUP_CHANGE_NETWORK_STATE = 'AUP_CHANGE_NETWORK_STATE';
  AUP_CHANGE_WIFI_MULTICAST_STATE = 'AUP_CHANGE_WIFI_MULTICAST_STATE';
  AUP_CHANGE_WIFI_STATE = 'AUP_CHANGE_WIFI_STATE';
  AUP_COM_VENDING_BILLING = 'AUP_COM_VENDING_BILLING';
  AUP_DISABLE_KEYGUARD = 'AUP_DISABLE_KEYGUARD';
  AUP_EXPAND_STATUS_BAR = 'AUP_EXPAND_STATUS_BAR';
  AUP_FLASHLIGHT = 'AUP_FLASHLIGHT';
  AUP_FOREGROUND_SERVICE = 'AUP_FOREGROUND_SERVICE';
  AUP_GET_PACKAGE_SIZE = 'AUP_GET_PACKAGE_SIZE';
  AUP_GET_TASKS = 'AUP_GET_TASKS';
  AUP_GLOBAL_SEARCH = 'AUP_GLOBAL_SEARCH';
  AUP_INSTALL_SHORTCUT = 'AUP_INSTALL_SHORTCUT';
  AUP_INSTANT_APP_FOREGROUND_SERVICE = 'AUP_INSTANT_APP_FOREGROUND_SERVICE';
  AUP_INTERNET = 'AUP_INTERNET';
  AUP_KILL_BACKGROUND_PROCESSES = 'AUP_KILL_BACKGROUND_PROCESSES';
  AUP_MANAGE_OWN_CALLS = 'AUP_MANAGE_OWN_CALLS';
  AUP_MODIFY_AUDIO_SETTINGS = 'AUP_MODIFY_AUDIO_SETTINGS';
  AUP_NFC_TRANSACTION_EVENT = 'AUP_NFC_TRANSACTION_EVENT';
  AUP_NFC = 'AUP_NFC';
  AUP_PACKAGE_USAGE_STATS = 'AUP_PACKAGE_USAGE_STATS';
  AUP_READ_GSERVICES = 'AUP_READ_GSERVICES';
  AUP_READ_SYNC_SETTINGS = 'AUP_READ_SYNC_SETTINGS';
  AUP_READ_SYNC_STATS = 'AUP_READ_SYNC_STATS';
  AUP_RECEIVE_BOOT_COMPLETED = 'AUP_RECEIVE_BOOT_COMPLETED';
  AUP_REORDER_TASKS = 'AUP_REORDER_TASKS';
  AUP_REQUEST_COMPANION_RUN_IN_BACKGROUND = 'AUP_REQUEST_COMPANION_RUN_IN_BACKGROUND';
  AUP_REQUEST_COMPANION_USE_DATA_IN_BACKGROUND = 'AUP_REQUEST_COMPANION_USE_DATA_IN_BACKGROUND';
  AUP_REQUEST_DELETE_PACKAGES = 'AUP_REQUEST_DELETE_PACKAGES';
  AUP_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS = 'AUP_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS';
  AUP_SET_ALARM = 'AUP_SET_ALARM';
  AUP_SET_WALLPAPER_HINTS = 'AUP_SET_WALLPAPER_HINTS';
  AUP_SET_WALLPAPER = 'AUP_SET_WALLPAPER';
  AUP_SUBSCRIBED_FEEDS_READ = 'AUP_SUBSCRIBED_FEEDS_READ';
  AUP_TRANSMIT_IR = 'AUP_TRANSMIT_IR';
  AUP_USE_BIOMETRIC = 'AUP_USE_BIOMETRIC';
  AUP_USE_FINGERPRINT = 'AUP_USE_FINGERPRINT';
  AUP_VIBRATE = 'AUP_VIBRATE';
  AUP_WAKE_LOCK = 'AUP_WAKE_LOCK';
  AUP_WRITE_SYNC_SETTINGS = 'AUP_WRITE_SYNC_SETTINGS';
  AUP_WRITE_USER_DICTIONARY = 'AUP_WRITE_USER_DICTIONARY';

  // DANGEROUS (RUNTIME USER APROVAL)

  AUP_ACCESS_COARSE_LOCATION = 'AUP_ACCESS_COARSE_LOCATION';
  AUP_ACCESS_FINE_LOCATION = 'AUP_ACCESS_FINE_LOCATION';
  AUP_ACCESS_MOCK_LOCATION = 'AUP_ACCESS_MOCK_LOCATION';
  AUP_ADD_VOICEMAIL = 'AUP_ADD_VOICEMAIL';
  AUP_ANSWER_PHONE_CALLS = 'AUP_ANSWER_PHONE_CALLS';
  AUP_AUTHENTICATE_ACCOUNTS = 'AUP_AUTHENTICATE_ACCOUNTS';
  AUP_BODY_SENSORS = 'AUP_BODY_SENSORS';
  AUP_CALL_PHONE = 'AUP_CALL_PHONE';
  AUP_CAMERA = 'AUP_CAMERA';
  AUP_ACCEPT_HANDOVER = 'AUP_ACCEPT_HANDOVER';
  AUP_GET_ACCOUNTS = 'AUP_GET_ACCOUNTS';
  AUP_MANAGE_ACCOUNTS = 'AUP_MANAGE_ACCOUNTS';
  AUP_PROCESS_OUTGOING_CALLS = 'AUP_PROCESS_OUTGOING_CALLS';
  AUP_READ_CALENDAR = 'AUP_READ_CALENDAR';
  AUP_READ_PHONE_STATE = 'AUP_READ_PHONE_STATE';
  AUP_READ_CALL_LOG = 'AUP_READ_CALL_LOG';
  AUP_READ_CONTACTS = 'AUP_READ_CONTACTS';
  AUP_READ_EXTERNAL_STORAGE = 'AUP_READ_EXTERNAL_STORAGE';
  AUP_READ_HISTORY_BOOKMARKS = 'AUP_READ_HISTORY_BOOKMARKS';
  AUP_READ_PHONE_NUMBERS = 'AUP_READ_PHONE_NUMBERS';
  AUP_READ_PROFILE = 'AUP_READ_PROFILE';
  AUP_READ_SMS = 'AUP_READ_SMS';
  AUP_READ_SOCIAL_STREAM = 'AUP_READ_SOCIAL_STREAM';
  AUP_READ_USER_DICTIONARY = 'AUP_READ_USER_DICTIONARY';
  AUP_RECEIVE_MMS = 'AUP_RECEIVE_MMS';
  AUP_RECEIVE_SMS = 'AUP_RECEIVE_SMS';
  AUP_RECEIVE_WAP_PUSH = 'AUP_RECEIVE_WAP_PUSH';
  AUP_RECORD_AUDIO = 'AUP_RECORD_AUDIO';
  AUP_SEND_SMS = 'AUP_SEND_SMS';
  AUP_SUBSCRIBED_FEEDS_WRITE = 'AUP_SUBSCRIBED_FEEDS_WRITE';
  AUP_UNINSTALL_SHORTCUT = 'AUP_UNINSTALL_SHORTCUT';
  AUP_USE_CREDENTIALS = 'AUP_USE_CREDENTIALS';
  AUP_USE_SIP = 'AUP_USE_SIP';
  AUP_WRITE_CALENDAR = 'AUP_WRITE_CALENDAR';
  AUP_WRITE_CALL_LOG = 'AUP_WRITE_CALL_LOG';
  AUP_WRITE_CONTACTS = 'AUP_WRITE_CONTACTS';
  AUP_WRITE_EXTERNAL_STORAGE = 'AUP_WRITE_EXTERNAL_STORAGE';
  AUP_WRITE_HISTORY_BOOKMARKS = 'AUP_WRITE_HISTORY_BOOKMARKS';
  AUP_WRITE_SOCIAL_STREAM = 'AUP_WRITE_SOCIAL_STREAM';
  AUP_WRITE_PROFILE = 'AUP_WRITE_PROFILE';
  AUP_WRITE_SMS = 'AUP_WRITE_SMS';

  // SIGNATURE (MATCHING CERTIFICATE)
  AUP_BIND_ACCESSIBILITY_SERVICE = 'AUP_BIND_ACCESSIBILITY_SERVICE';
  AUP_BIND_AUTOFILL_SERVICE = 'AUP_BIND_AUTOFILL_SERVICE';
  AUP_BIND_SCREENING_SERVICE = 'AUP_BIND_SCREENING_SERVICE';
  AUP_BIND_CARRIER_MESSAGING_SERVICE = 'AUP_BIND_CARRIER_MESSAGING_SERVICE';
  AUP_BIND_CARRIER_SERVICES = 'AUP_BIND_CARRIER_SERVICES';
  AUP_BIND_CHOOSER_TARGET_SERVICE = 'AUP_BIND_CHOOSER_TARGET_SERVICE';
  AUP_BIND_CONDITION_PROVIDER_SERVICE = 'AUP_BIND_CONDITION_PROVIDER_SERVICE';
  AUP_BIND_DEVICE_ADMIN = 'AUP_BIND_DEVICE_ADMIN';
  AUP_BIND_DREAM_SERVICE = 'AUP_BIND_DREAM_SERVICE';
  AUP_BIND_INCALL_SERVICE = 'AUP_BIND_INCALL_SERVICE';
  AUP_BIND_INPUT_METHOD = 'AUP_BIND_INPUT_METHOD';
  AUP_BIND_NFC_SERVICE = 'AUP_BIND_NFC_SERVICE';
  AUP_BIND_MIDI_DEVICE_SERVICE = 'AUP_BIND_MIDI_DEVICE_SERVICE';
  AUP_BIND_NOTIFICATION_LISTENER_SERVICE = 'AUP_BIND_NOTIFICATION_LISTENER_SERVICE';
  AUP_BIND_PRINT_SERVICE = 'AUP_BIND_PRINT_SERVICE';
  AUP_BIND_QUICK_SETTINGS_TILE = 'AUP_BIND_QUICK_SETTINGS_TILE';
  AUP_BIND_REMOTEVIEWS = 'AUP_BIND_REMOTEVIEWS';
  AUP_BIND_TELECOM_CONNECTION_SERVICE = 'AUP_BIND_TELECOM_CONNECTION_SERVICE';
  AUP_BIND_TEXT_SERVICE = 'AUP_BIND_TEXT_SERVICE';
  AUP_BIND_TV_INPUT = 'AUP_BIND_TV_INPUT';
  AUP_BIND_VISUAL_VOICEMAIL_SERVICE = 'AUP_BIND_VISUAL_VOICEMAIL_SERVICE';
  AUP_BIND_VOICE_INTERACTION = 'AUP_BIND_VOICE_INTERACTION';
  AUP_BIND_VPN_SERVICE = 'AUP_BIND_VPN_SERVICE';
  AUP_BIND_VR_LISTENER_SERVICE = 'AUP_BIND_VR_LISTENER_SERVICE';
  AUP_CLEAR_APP_CACHE = 'AUP_CLEAR_APP_CACHE';
  AUP_BIND_WALLPAPER = 'AUP_BIND_WALLPAPER';
  AUP_REQUEST_INSTALL_PACKAGES = 'AUP_REQUEST_INSTALL_PACKAGES';
  AUP_MANAGE_DOCUMENTS = 'AUP_MANAGE_DOCUMENTS';
  AUP_READ_VOICEMAIL = 'AUP_READ_VOICEMAIL';
  AUP_SYSTEM_ALERT_WINDOW = 'AUP_SYSTEM_ALERT_WINDOW';
  AUP_WRITE_SETTINGS = 'AUP_WRITE_SETTINGS';
  AUP_WRITE_VOICEMAIL = 'AUP_WRITE_VOICEMAIL';

implementation

end.

